-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.city
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "City_Car" text COLLATE pg_catalog."default",
    CONSTRAINT city_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "city_City_Car_key" UNIQUE ("City_Car")
);

CREATE TABLE IF NOT EXISTS public.fuel
(
    "CityMileage" double precision,
    "HighwayMileage" double precision,
    "FuelType" text COLLATE pg_catalog."default",
    "FuelCapacity" double precision,
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Vin" text COLLATE pg_catalog."default",
    CONSTRAINT fuel_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.make
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Make_Car" text COLLATE pg_catalog."default",
    CONSTRAINT vehicle_brand_pkey PRIMARY KEY ("Id"),
    CONSTRAINT make_make_car_key UNIQUE ("Make_Car")
);

CREATE TABLE IF NOT EXISTS public.market_value
(
    "InvoicePrice" double precision,
    "BelowMarketPrice" double precision,
    "AverageMarketPrice" double precision,
    "AboveMarketPrice" double precision,
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Vin" text COLLATE pg_catalog."default",
    CONSTRAINT market_value_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.model
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Model_Car" text COLLATE pg_catalog."default",
    CONSTRAINT model_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "model_Model_Car_key" UNIQUE ("Model_Car")
);

CREATE TABLE IF NOT EXISTS public.safety_rating
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Vin" text COLLATE pg_catalog."default",
    "RoofStrengthTestResults" text COLLATE pg_catalog."default",
    "RearCrashProtectionHeadRestraintRatings" text COLLATE pg_catalog."default",
    "SmallOverlapFrontTestResults" text COLLATE pg_catalog."default",
    "ModerateOverlapFrontTestResults" text COLLATE pg_catalog."default",
    "SideImpactTestResults" text COLLATE pg_catalog."default",
    CONSTRAINT safety_rating_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.specifications_car
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Vin" text COLLATE pg_catalog."default",
    "TrimPremiumPackage" text COLLATE pg_catalog."default",
    "CountryOrigin" text COLLATE pg_catalog."default",
    "VehicleType" text COLLATE pg_catalog."default",
    "VehicleSize" text COLLATE pg_catalog."default",
    "TransmissionType" text COLLATE pg_catalog."default",
    "Doors" integer,
    CONSTRAINT specifications_car_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.state
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "State_Car" text COLLATE pg_catalog."default",
    CONSTRAINT state_pkey PRIMARY KEY ("Id"),
    CONSTRAINT "state_State_Car_key" UNIQUE ("State_Car")
);

CREATE TABLE IF NOT EXISTS public.true_car_listings
(
    "Id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    "Price" bigint,
    "Year" bigint,
    "Mileage" bigint,
    "City" text COLLATE pg_catalog."default",
    "State" text COLLATE pg_catalog."default",
    "Vin" text COLLATE pg_catalog."default",
    "Make" text COLLATE pg_catalog."default",
    "Model" text COLLATE pg_catalog."default",
    "InformacionActualizada" boolean DEFAULT false,
    CONSTRAINT true_car_listings_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.true_cars_test
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Price" bigint,
    "Year" integer,
    "Mileage" bigint,
    "City" text COLLATE pg_catalog."default",
    "State" text COLLATE pg_catalog."default",
    "Vin" text COLLATE pg_catalog."default",
    "Make" text COLLATE pg_catalog."default",
    "Model" text COLLATE pg_catalog."default",
    "InformacionActualizada" boolean DEFAULT false,
    CONSTRAINT true_cars_test_pkey PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.true_cars_train
(
    "Id" integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Price" bigint,
    "Year" integer,
    "Mileage" bigint,
    "City" text COLLATE pg_catalog."default",
    "State" text COLLATE pg_catalog."default",
    "Vin" text COLLATE pg_catalog."default",
    "Make" text COLLATE pg_catalog."default",
    "Model" text COLLATE pg_catalog."default",
    "InformacionActualizada" boolean DEFAULT false,
    CONSTRAINT true_cars_train_pkey PRIMARY KEY ("Id")
);

ALTER TABLE IF EXISTS public.fuel
    ADD FOREIGN KEY ("Vin")
    REFERENCES public.true_car_listings ("Vin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.market_value
    ADD FOREIGN KEY ("Vin")
    REFERENCES public.true_car_listings ("Vin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.safety_rating
    ADD FOREIGN KEY ("Vin")
    REFERENCES public.true_car_listings ("Vin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.specifications_car
    ADD FOREIGN KEY ("Vin")
    REFERENCES public.true_car_listings ("Vin") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.true_car_listings
    ADD FOREIGN KEY ("City")
    REFERENCES public.city ("City_Car") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.true_car_listings
    ADD FOREIGN KEY ("Make")
    REFERENCES public.make ("Make_Car") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.true_car_listings
    ADD FOREIGN KEY ("Model")
    REFERENCES public.model ("Model_Car") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.true_car_listings
    ADD FOREIGN KEY ("State")
    REFERENCES public.state ("State_Car") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;